
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t donpete007/portfolio .

      
      - name: push images
        run: | 
            docker login -u donpete007 -p ${{secrets.REGISTRY_PASS}}
            docker push donpete007/portfolio